### ISSUE TITLE
Add download mode for episodes file

### ISSUE THREAD

**Issue by yairp03** [yairp03/HoradotTV#67]
There's an option to export failed episodes to a file (currently with the `.epis` extension).
There should be an option to load this file into downloading

**Comment by bigdrex16** [comment]
@yairp03 can you elaborate? We have the 'download episode' option which allows to select a specific season and episode, so I don't understand what we want to do here exactly.

**Comment by yairp03** [comment]
@bigdrex16 updated the issue description

**Comment by bigdrex16** [comment]
@yairp03 any chance you have an existing real-life example of this file to make this development a bit quicker?

**Comment by bigdrex16** [comment]
Also, let's talk UX for a second: after the user searched for the show, we will have another download mode:
`[5] Download from Episodes File (.epis)`
By selecting it, the user will need to provide the full URL of this file? Or do we want to search in the same download folder, under the show's sub-folder, for all .epis files and let him select (by selecting the file's number). If so, I suggest descending order from last to first (by the file's modified date, as it might got renamed by the user at some point).

**Comment by yairp03** [comment]
As for the file format, currently, it's just a JSON dump of a `List<EpisodeInformation>` type.
As for the download mode, I think the search is unnecessary if user just want to download from an episode file, cause it has the information about the series already.
We can use the fact that search is on 2 characters at least to use one character strings as commands, for example, `q` to quit and `f` to download from a file

**Comment by bigdrex16** [comment]
And how about the file selection? We can do a recursive search inside all the directories under the downloads folder, or provide a full path. I think the first option is way friendlier, and we should also provide an option at the end to delete this file if everything went fine, or updating it according to the last result (if some episodes were downloaded successfully and some still didn't).

**Comment by yairp03** [comment]
Let's start by asking for a directory of the file, suggesting the last location, and searching there for `.epis` files

**Comment by bigdrex16** [comment]
@yairp03 another idea that I believe is better, tell me what your thoughts are:
- There will be a single JSON for the app, stored in the installation folder (like the configuration file).
- This JSON will contain all the episodes for all the shows that we were unable to download.
- It will be automatically saved if there were any errors. Episodes (and shows) will be added or removed automatically according to the download status. Meaning: if we retried to download an episode, and it was successful, we will remove it from the JSON.
- The user won't have to be aware of this file at all, and won't need to specify any path for it. When the app starts, if he asks to retry and download episodes by using the `f` command, the app will print the list of shows we have in our JSON, allows him to select the relevant show, and from there everything will continue as we planned.

**Comment by yairp03** [comment]
This solution sounds good for a better UX, but is also, in my opinion, a little overpowered for a console application.
When I'll get back to work on the GUI app, this solution is better.
